/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.lavanderia.view;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.lavanderia.controller.PelangganController;
import project.lavanderia.model.TabelPelangganModel;
import project.lavanderia.entity.Pelanggan;
import project.lavanderia.database.LavanderiaDatabase;
import project.lavanderia.model.PelangganModel;
import project.lavanderia.event.PelangganListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author Dean
 */
public class AmbilPesananView extends javax.swing.JPanel implements PelangganListener,ListSelectionListener{
    private LavanderiaDatabase db;
    private TabelPelangganModel tabelModel;
    private Pelanggan pelanggan;
    private DefaultTableModel tabModel;
    private String key;
    private PelangganModel model;
    private PelangganController controller;

    
    /**
     * Creates new form AmbilPesananView
     */
    public AmbilPesananView() {
        initComponents();
        tabelModel = new TabelPelangganModel();
        tabelDataPesanan.setModel(tabelModel);
        getData();        
    }

    public void getData( ){
        try{
            Statement stat = LavanderiaDatabase.getConnection().createStatement();
            String sql  = "Select * from PELANGGAN";
            ResultSet res   = stat.executeQuery(sql);
            while(res.next()){
                pelanggan = new Pelanggan();
                pelanggan.setNoid(res.getInt("NOID"));
                pelanggan.setTanggal(res.getString("TANGGAL"));
                pelanggan.setNama(res.getString("NAMA"));
                pelanggan.setAlamat(res.getString("ALAMAT"));
                pelanggan.setTelp(res.getString("TELP"));
                pelanggan.setJenis(res.getString("JENIS"));
                pelanggan.setBerat(res.getDouble("BERAT"));
                pelanggan.setHarga(res.getDouble("HARGA"));
                
                tabelModel.add(pelanggan);                
            }
        } catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }
    }
    
    private void cariData(String key){
        for (int i=0; i<=999; i++){
            tabelModel.remove(tabelDataPesanan.getSelectedRowCount());
            if (tabelDataPesanan.getRowCount()==0){
                i = 999;
            }
        }
        try{
            Statement stat = LavanderiaDatabase.getConnection().createStatement();
            String sql  = "SELECT * from PELANGGAN WHERE NOID LIKE '%"+key+"%' OR NAMA LIKE '%"+key+"%' OR ALAMAT LIKE '%"+key+"%'";
            ResultSet res   = stat.executeQuery(sql);
            while(res.next()){
                pelanggan = new Pelanggan();
                pelanggan.setNoid(res.getInt("NOID"));
                pelanggan.setTanggal(res.getString("TANGGAL"));
                pelanggan.setNama(res.getString("NAMA"));
                pelanggan.setAlamat(res.getString("ALAMAT"));
                pelanggan.setTelp(res.getString("TELP"));
                pelanggan.setJenis(res.getString("JENIS"));
                pelanggan.setBerat(res.getDouble("BERAT"));
                pelanggan.setHarga(res.getDouble("HARGA"));
                
                tabelModel.add(pelanggan);                
            }
        } catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataPesanan = new javax.swing.JTable();
        btnAmbil = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RefreshBtn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(181, 174, 236));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ambil Pesanan");

        txtCari.setBackground(new java.awt.Color(230, 207, 236));
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        tabelDataPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelDataPesanan.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabelDataPesananComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDataPesanan);

        btnAmbil.setBackground(new java.awt.Color(10, 212, 66));
        btnAmbil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAmbilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAmbilMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAmbilMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("AMBIL");

        javax.swing.GroupLayout btnAmbilLayout = new javax.swing.GroupLayout(btnAmbil);
        btnAmbil.setLayout(btnAmbilLayout);
        btnAmbilLayout.setHorizontalGroup(
            btnAmbilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAmbilLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        btnAmbilLayout.setVerticalGroup(
            btnAmbilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAmbilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/lavanderia/view/searchfind.jpg"))); // NOI18N
        jLabel3.setText("Cari Data Pelanggan");

        RefreshBtn.setBackground(new java.awt.Color(0, 204, 255));
        RefreshBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RefreshBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RefreshBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RefreshBtnMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("REFRESH");

        javax.swing.GroupLayout RefreshBtnLayout = new javax.swing.GroupLayout(RefreshBtn);
        RefreshBtn.setLayout(RefreshBtnLayout);
        RefreshBtnLayout.setHorizontalGroup(
            RefreshBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RefreshBtnLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel4)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        RefreshBtnLayout.setVerticalGroup(
            RefreshBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        
    }//GEN-LAST:event_txtCariKeyReleased

    private void tabelDataPesananComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabelDataPesananComponentShown

    }//GEN-LAST:event_tabelDataPesananComponentShown

    private void btnAmbilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAmbilMousePressed
        try{
            int selectedRow = tabelDataPesanan.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Data belum dipilih");
            } else {
            Object rowID = tabelModel.getValueAt(selectedRow,0);
            String sql  = "INSERT INTO pesanan_ambil (`NOID`,`TANGGAL`,`NAMA`,`ALAMAT`,`TELP`,`JENIS`,`BERAT`,`HARGA`)"
                          + "(SELECT `NOID`,`TANGGAL`,`NAMA`,`ALAMAT`,`TELP`,`JENIS`,`BERAT`,`HARGA` FROM pelanggan WHERE NOID = "+rowID+")";
            
            String delete = "DELETE FROM pelanggan WHERE NOID = "+ rowID +"";
            
            Connection conn = LavanderiaDatabase.getConnection();
            PreparedStatement preparedStmt = conn.prepareStatement(sql);
            PreparedStatement PS2 = conn.prepareStatement(delete);
            preparedStmt.execute();
            PS2.execute();
            JOptionPane.showMessageDialog(null, "Data dengan ID "+ rowID + " sudah di ambil");
            tabelModel.remove(selectedRow);
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, new Object[]{"Terjadi error dengan pesan ", ex.getMessage()});
        }        
    }//GEN-LAST:event_btnAmbilMousePressed

    private void btnAmbilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAmbilMouseEntered
        btnAmbil.setBackground(new Color(0 ,187 ,41));
    }//GEN-LAST:event_btnAmbilMouseEntered

    private void btnAmbilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAmbilMouseExited
        btnAmbil.setBackground(new Color(10,212,66));
    }//GEN-LAST:event_btnAmbilMouseExited

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        key = txtCari.getText();
        System.out.println(key);
        try {
            if(key!=""){
            cariData(key);
        } else if (tabelDataPesanan.getRowCount() == 0){
            txtCari.setText(null);
            getData();
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan");            
        } else {
            getData();
        }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, new Object[]{"Terjadi error! Mohon restart aplikasi!", ex.getMessage()});
        } 
        
    }//GEN-LAST:event_txtCariActionPerformed

    private void RefreshBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshBtnMousePressed
        for (int i=0; i<=999; i++){
            tabelModel.remove(tabelDataPesanan.getSelectedRowCount());
            if (tabelDataPesanan.getRowCount()==0){
                i = 999;
            }
        }
        getData();
    }//GEN-LAST:event_RefreshBtnMousePressed

    private void RefreshBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshBtnMouseEntered
       RefreshBtn.setBackground(new Color(0 ,179, 230));
    }//GEN-LAST:event_RefreshBtnMouseEntered

    private void RefreshBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshBtnMouseExited
        RefreshBtn.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_RefreshBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RefreshBtn;
    private javax.swing.JPanel btnAmbil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable tabelDataPesanan;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(PelangganModel model) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void onInsert(Pelanggan pelanggan) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void onDelete() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void onUpdate(Pelanggan pelanggan) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
