/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.lavanderia.view;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import project.lavanderia.model.TabelPesananModel;
import project.lavanderia.database.LavanderiaDatabase;
import project.lavanderia.entity.Pesanan;


/**
 *
 * @author ryzen
 */
public class DataTerambilView extends javax.swing.JPanel {

    private LavanderiaDatabase db;
    private TabelPesananModel model;
    private Pesanan pesanan;
    private DefaultTableModel tabModel;
    private MainFrame frame;
    /**
     * Creates new form DataTerambil
     */
    public DataTerambilView() {
        initComponents();
        model = new TabelPesananModel();
        TablePesanan.setModel(model);
        getData();
    }
    
    public void getData( ){
        try{
            Statement stat = LavanderiaDatabase.getConnection().createStatement();
            String sql  = "Select * from pesanan_ambil";
            ResultSet res   = stat.executeQuery(sql);
            while(res.next()){
                pesanan = new Pesanan();
                pesanan.setNoid(res.getInt("NOID"));
                pesanan.setTanggal(res.getString("TANGGAL"));
                pesanan.setNama(res.getString("NAMA"));
                pesanan.setAlamat(res.getString("ALAMAT"));
                pesanan.setTelp(res.getString("TELP"));
                pesanan.setJenis(res.getString("JENIS"));
                pesanan.setBerat(res.getDouble("BERAT"));
                pesanan.setHarga(res.getDouble("HARGA"));

                model.add(pesanan);
            }
        } catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePesanan = new javax.swing.JTable();
        RefreshBtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        HapusBtn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 251, 255));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 48)); // NOI18N
        jLabel1.setText("Data Terambil");

        TablePesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablePesanan);

        RefreshBtn.setBackground(new java.awt.Color(0, 204, 255));
        RefreshBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RefreshBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RefreshBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RefreshBtnMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REFRESH");

        javax.swing.GroupLayout RefreshBtnLayout = new javax.swing.GroupLayout(RefreshBtn);
        RefreshBtn.setLayout(RefreshBtnLayout);
        RefreshBtnLayout.setHorizontalGroup(
            RefreshBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RefreshBtnLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18))
        );
        RefreshBtnLayout.setVerticalGroup(
            RefreshBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        HapusBtn.setBackground(new java.awt.Color(255, 51, 51));
        HapusBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HapusBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HapusBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HapusBtnMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HAPUS");

        javax.swing.GroupLayout HapusBtnLayout = new javax.swing.GroupLayout(HapusBtn);
        HapusBtn.setLayout(HapusBtnLayout);
        HapusBtnLayout.setHorizontalGroup(
            HapusBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HapusBtnLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(24, 24, 24))
        );
        HapusBtnLayout.setVerticalGroup(
            HapusBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(HapusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabel1)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RefreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HapusBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshBtnMousePressed
       //try {
            //Object[] judul_kolom = {"NOID","TANGGAL", "NAMA", "ALAMAT", "TELP", "JENIS", "BERAT", "HARGA"};
            //tabModel=new DefaultTableModel(null,judul_kolom);
            //TablePesanan.setModel(tabModel);
            
            //Statement stat = LavanderiaDatabase.getConnection().createStatement();
            //String sql  = "Select * from PESANAN_AMBIL";
            //ResultSet res   = stat.executeQuery(sql);             
            //while(res.next()){
                //Object[] data={
                    //res.getString("NOID"),
                   //res.getString("TANGGAL"),
                    //res.getString("NAMA"),                    
                   //res.getString("ALAMAT"),
                    //res.getString("TELP"),
                   //res.getString("JENIS"),
                    //res.getString("BERAT"),
                   //res.getString("HARGA"),
                //};
               //tabModel.addRow(data);
           // }             
       // } catch (Exception ex) {
        //JOptionPane.showMessageDialog(this, new Object[]{"Terjadi error dengan pesan ", ex.getMessage()});
        //}
        
        
    }//GEN-LAST:event_RefreshBtnMousePressed

    private void HapusBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HapusBtnMousePressed
        try{
            int selectedRow = TablePesanan.getSelectedRow();
            Object rowID = model.getValueAt(selectedRow,0);
            
            String delete = "DELETE FROM pesanan_ambil WHERE NOID = "+ rowID +"";
            
            Connection conn = LavanderiaDatabase.getConnection();
            PreparedStatement PS = conn.prepareStatement(delete);
            PS.execute();
            JOptionPane.showMessageDialog(null, "Data dengan ID "+ rowID + " sudah di hapus");
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, new Object[]{"Terjadi error dengan pesan ", ex.getMessage()});
        }
    }//GEN-LAST:event_HapusBtnMousePressed

    private void RefreshBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshBtnMouseEntered
       RefreshBtn.setBackground(new Color(0 ,179, 230));
        
    }//GEN-LAST:event_RefreshBtnMouseEntered

    private void RefreshBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshBtnMouseExited
        RefreshBtn.setBackground(new Color(0,204,255));
    }//GEN-LAST:event_RefreshBtnMouseExited

    private void HapusBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HapusBtnMouseEntered
        HapusBtn.setBackground(new Color(230 ,26, 26));
    }//GEN-LAST:event_HapusBtnMouseEntered

    private void HapusBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HapusBtnMouseExited
        HapusBtn.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_HapusBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HapusBtn;
    private javax.swing.JPanel RefreshBtn;
    private javax.swing.JTable TablePesanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
